### ISSUE TITLE
Variables related to apartments in Nord, Down and Residental

### ISSUE THREAD

**Issue by heromaster** [morgolon/glife#11]
In the community version they are named arrays var['Street', 'Down', 'Nord']. In the 1.0.5 version it does not exists anymore and pointing to a single var for the residental district.

Seems like in the RUS version you can only buy/rent the apartment in the residental area. What should be done with this change? Keep the community version or replace them with the RUS version?

**Comment by morgolon** [comment]
I vote for going with the RUS version on this one, as the current apartment situation is bugged anyway.
